name: MagicStick
version: 1.0
main: com.shynee.spigot.Spigot
api-version: 1.17
author: Shynee
description: A port of Hypixel's "Magic Toy Stick" victory dance
commands:
  magicstick:
    usage: /<command>
    description: Gives the player the Magic Toy Stick item
